apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-operator-config
  namespace: openshift-storage
data:
  CSI_LOG_LEVEL: '5'
  CSI_PLUGIN_TOLERATIONS: |-

    - key: node.ocs.openshift.io/storage
      operator: Equal
      value: "true"
      effect: NoSchedule
  CSI_PROVISIONER_TOLERATIONS: |-

    - key: node.ocs.openshift.io/storage
      operator: Equal
      value: "true"
      effect: NoSchedule
  ROOK_CSI_KUBELET_DIR_PATH: /var/data/kubelet